import 'package:equatable/equatable.dart';

class Product extends Equatable {
  final String name;
  final String category;
  final double price;
  final String imageUrl;
  final bool isRecommended;
  final bool isPopular;
  final bool isRecentlyadded;
  final bool isDrink;

  const Product({
    required this.name,
    required this.category,
    required this.price,
    required this.imageUrl,
    required this.isRecommended,
    required this.isPopular,
    required this.isRecentlyadded,
    required this.isDrink,
  });
  @override
  List<Object?> get props => [
        name,
        category,
        price,
        imageUrl,
        isRecommended,
        isPopular,
        isRecentlyadded,
        isDrink
      ];

  static List<Product> products = [
    Product(
      name: "soft drink",
      category: "Drink",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "biryani",
      category: "vospesrin",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/apet.jpg',
    ),
    Product(
      name: "vodka",
      category: " drinks",
      price: 2.99,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/drink.jpg',
    ),
    Product(
      name: "soft drink",
      category: "soft drinks",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "soft drink",
      category: "Drink",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "biryani",
      category: "vospesrin",
      price: 2.99,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imageUrl: 'images/apet.jpg',
    ),
    Product(
      name: "vodka",
      category: " drinks",
      price: 2.99,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imageUrl: 'images/drink.jpg',
    ),
    Product(
      name: "soft drink",
      category: "soft drinks",
      price: 2.99,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imageUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "soft drink",
      category: "Drink",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imageUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "biryani",
      category: "vospesrin",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imageUrl: 'images/apet.jpg',
    ),
    Product(
      name: "vodka",
      category: " drinks",
      price: 2.99,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/drink.jpg',
    ),
    Product(
      name: "soft drink",
      category: "soft drinks",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imageUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "soft drink",
      category: "Drink",
      price: 2.99,
      isPopular: true,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "biryani",
      category: "vospesrin",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imageUrl: 'images/apet.jpg',
    ),
    Product(
      name: "vodka",
      category: " drinks",
      price: 2.99,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: true,
      isDrink: false,
      imageUrl: 'images/drink.jpg',
    ),
    Product(
      name: "soft drink",
      category: "soft drinks",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "soft drink",
      category: "Drink",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "biryani",
      category: "vospesrin",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/apet.jpg',
    ),
    Product(
      name: "vodka",
      category: " drinks",
      price: 2.99,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/drink.jpg',
    ),
    Product(
      name: "soft drink",
      category: "soft drinks",
      price: 2.99,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imageUrl: 'images/biryani.jpg',
    ),
  ];
}
