import 'package:equatable/equatable.dart';
import 'package:get/get_connect/http/src/utils/utils.dart';

class Product extends Equatable {
  final String name;
  final String category;
  final double price;
  final String imaUrl;
  final bool isRecommended;
  final bool isPopular;
  final bool isRecentlyadded;
  final bool isDrink;

  const Product({
    required this.name,
    required this.category,
    required this.price,
    required this.imaUrl,
    required this.isRecommended,
    required this.isPopular,
    required this.isRecentlyadded,
    required this.isDrink,
  });
  @override
  List<Object?> get props => [
        name,
        category,
        price,
        imaUrl,
        isRecommended,
        isPopular,
        isRecentlyadded,
        isDrink
      ];

  static List<Product> products = [
    Product(
      name: "Elotes",
      category: "Vorspeisen",
      price: 3.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Onionringe",
      category: "Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/apet.jpg',
    ),
    Product(
      name: "Chip con tres salas",
      category: " Vorspeisen",
      price: 5.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/drink.jpg',
    ),
    Product(
      name: "Nachos Arriba",
      category: "Vorspeisen",
      price: 6.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Nachos Mexicana",
      category: "Vorspeisen",
      price: 2.99,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Nachos con pollo",
      category: "Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/apet.jpg',
    ),
    Product(
      name: "Nachos con picadillo",
      category: " Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/drink.jpg',
    ),
    Product(
      name: "Chilli chese Nuggets",
      category: "Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Peppers Red Hot",
      category: "Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Buffalo-Chicken Wings",
      category: "Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/apet.jpg',
    ),
    Product(
      name: "Mozzarella- Sticks",
      category: " Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/drink.jpg',
    ),
    Product(
      name: "Peppers-Cheddar",
      category: "Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Scampi vom Grill",
      category: "Vorspeisen",
      price: 7.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Tex Mex Teller",
      category: "Vorspeisen",
      price: 8.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/apet.jpg',
    ),
    Product(
      name: "Peppers Habaneros",
      category: " Vorspeisen",
      price: 8.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/drink.jpg',
    ),
    Product(
      name: "Mythra Teller",
      category: "Vorspeisen",
      price: 7.50,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Cream de Elote",
      category: "Salad",
      price: 3.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/OIP.jpg',
    ),
    Product(
      name: "Sopa de Pomodoro",
      category: "Salad",
      price: 3.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/apet.jpg',
    ),
    Product(
      name: "Chilli con Carne",
      category: " Salad",
      price: 4.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/drink.jpg',
    ),
    Product(
      name: "El Goucho suppe",
      category: "Salad",
      price: 4.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Quesadillas Vegetariana",
      category: "Salad",
      price: 7.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Quesadillas con pollo",
      category: "Salad",
      price: 7.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Quesadillas con picadillo",
      category: "Salad",
      price: 7.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Quesadillas can Spinaci",
      category: "Salad",
      price: 7.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Quesadillas de Hongos",
      category: "Salad",
      price: 7.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Quesadillas arriba Mexico",
      category: "Salad",
      price: 7.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ensalada Mixta",
      category: "Salad",
      price: 4.20,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ensalada de Queso",
      category: "Salad",
      price: 4.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ensalada de Atun",
      category: "Salad",
      price: 5.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ensalada de Nopales",
      category: "Salad",
      price: 6.90,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ensalada arriba Mexico",
      category: "Salad",
      price: 7.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ensalada Ranchero",
      category: "Salad",
      price: 8.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ensalada Australia",
      category: "Salad",
      price: 8.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "pfifferlingsauce",
      category: "Apetizer",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Champignonsauce",
      category: "Apetizer",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Grun Pfeffersauce",
      category: "Apetizer",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gorgonzolasauce",
      category: "Apetizer",
      price: 2.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Avacadocream",
      category: "Apetizer",
      price: 2.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sauerrahm",
      category: "Apetizer",
      price: 2.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Salsa Raja",
      category: "Apetizer",
      price: 1.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Jalapenos",
      category: "Apetizer",
      price: 1.80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: true,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Likore Amaretto ",
      category: "Drinks",
      price: 1.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Baileys",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Southern Comfort",
      category: "Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sambuca",
      category: "Drinks",
      price: 1.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Batida de Coco",
      category: "Drinks",
      price: 1.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Kahlua",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Osborne Veterano",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Asbach Uralt",
      category: "Drinks",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Jacobi 1860 V.S.O.P",
      category: "Drinks",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Cardenal Mendoza",
      category: "Drinks",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Carlos 1",
      category: "Drinks",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Remy Martin V.S.O.P.",
      category: "Drinks",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Metaxa ****",
      category: "Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Calvados Papidoux",
      category: "Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Olmeca Tequila Blanco",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Olmeca Tequila Reposado",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sierra Tequila Silver",
      category: "Drinks",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sierra Tequila Reposado",
      category: "Drinks",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sierra Tequila Antiguo",
      category: "Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sierra Tequila Plata",
      category: "Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sierra Tequila Milinario Extra Añejo",
      category: "Drinks",
      price: 5.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "EL Jimador Blanco",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "EL Jimador Reposado",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fürst Bismarck",
      category: "Drinks",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Grappa",
      category: "Drinks",
      price: 1.80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Williamsbirne",
      category: "Drinks",
      price: 1.80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Whiskey Johnnie Walker Red",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Johnnie Walker black",
      category: "Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Ballanties",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "The Glenlivet",
      category: "Drinks",
      price: 3.80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chivas Regal",
      category: "Drinks",
      price: 3.80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "jim Beam",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "jack Danniels",
      category: "Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "James Irisch Wishkey",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Jack Danniel Honey",
      category: "Drinks",
      price: 3.80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Vodka Absolute Vodka",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Vodka Gorbatschow",
      category: "Drinks",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Parliment Vodka",
      category: "Drinks",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Finlandia",
      category: "Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Long Barcadi Cola",
      category: "Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gin Tonic",
      category: "Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Vodka Lemon",
      category: "Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: true,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Burrito de Verduras",
      category: "Apetizer",
      price: 9.20,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Burrito de Pollo",
      category: "Apetizer",
      price: 9.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Burrito de Picadillo",
      category: "Apetizer",
      price: 9.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Burrito de Pescado",
      category: "Apetizer",
      price: 9.20,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Tacos Arriba",
      category: "Apetizer",
      price: 9.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Tacos con pollo",
      category: "Apetizer",
      price: 9.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Tacos con picadillo",
      category: "Apetizer",
      price: 9.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Tacos con Verduras",
      category: "Apetizer",
      price: 9.20,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Burrito de Espinacas",
      category: "Apetizer",
      price: 9.50,
      isPopular: true,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chicken chilli",
      category: "MainCourse",
      price: 10.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chicken Madras",
      category: "MainCourse",
      price: 10.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chicken Himalya",
      category: "MainCourse",
      price: 10.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chicken Mango",
      category: "MainCourse",
      price: 10.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lamm lahori",
      category: "MainCourse",
      price: 13.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lamm Vindalo",
      category: "MainCourse",
      price: 13.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lamm Myhtra",
      category: "MainCourse",
      price: 13.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lamm Mango",
      category: "MainCourse",
      price: 13.90,
      isPopular: false,
      isRecommended: true,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Hüftsteak 200g**",
      category: "Hauptegricht Steaks",
      price: 12.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Hüftsteak 300g**",
      category: "Hauptegricht Steaks",
      price: 15.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Hüftsteak 400g**",
      category: "Hauptegricht Steaks",
      price: 18.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Entrecôte 200g**",
      category: "Hauptegricht Steaks",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Entrecôte 300g**",
      category: "Hauptegricht Steaks",
      price: 18.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Entrecôte 400g**",
      category: "Hauptegricht Steaks",
      price: 21.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Rumpsteak 200g**",
      category: "Hauptegricht Steaks",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Rumpsteak 300g**",
      category: "Hauptegricht Steaks",
      price: 18.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Rumpsteak 400g**",
      category: "Hauptegricht Steaks",
      price: 21.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Filetsteak 200g**",
      category: "Hauptegricht Steaks",
      price: 18.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Filetsteak 300g**",
      category: "Hauptegricht Steaks",
      price: 24.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Filetsteak 400g**",
      category: "Hauptegricht Steaks",
      price: 30.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pfeffersteak vom Rind 200g**",
      category: "Hauptegricht Steaks",
      price: 13.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pfeffersteak vom Rind 300g**",
      category: "Hauptegricht Steaks",
      price: 16.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pfeffersteak vom Rind 400g**",
      category: "Hauptegricht Steaks",
      price: 19.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Rostbraten 200g**",
      category: "Hauptegricht Steaks",
      price: 13.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Rostbraten 300g**",
      category: "Hauptegricht Steaks",
      price: 16.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Rostbraten 400g**",
      category: "Hauptegricht Steaks",
      price: 19.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lammfilet 200g**",
      category: "Hauptegricht Steaks",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lammfilet 300g**",
      category: "Hauptegricht Steaks",
      price: 18.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lammfilet 400g**",
      category: "Hauptegricht Steaks",
      price: 21.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pfifferlingsauce",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Champignonsauce",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Grüne Pfeffersauce",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gorgonzolasauce",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Avocadocréme",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sauerrahm",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Salsa Roja",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Jalapeños",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.80,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pommes frites",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Kroketten",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Backkartoffel",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Bratkartoffeln",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.60,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Patatas fritas",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Manioc",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Frojoles",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Champignonpfanne",
      category: "Acompanamientos Beilagen & Saucen",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Röstzwiebeln",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Grüne Bohnen",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "mexikanisches Verduras",
      category: "Acompanamientos Beilagen & Saucen",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Kräuterbutter",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Arriba - Brot",
      category: "Acompanamientos Beilagen & Saucen",
      price: 0.30,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Arroz",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Grilltomate",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Broccoli",
      category: "Acompanamientos Beilagen & Saucen",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Extra Käse",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Beilagesalat",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Bacon",
      category: "Acompanamientos Beilagen & Saucen",
      price: 1.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pechugas alla Parilla",
      category: "Arriba- Spezialitäten",
      price: 9.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pechugas poblano",
      category: "Arriba- Spezialitäten",
      price: 10.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pollo con Pina",
      category: "Arriba- Spezialitäten",
      price: 10.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Mole Verde á la Petitas",
      category: "Arriba- Spezialitäten",
      price: 10.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Mole Rojo de Cacahuate ",
      category: "Arriba- Spezialitäten",
      price: 11.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "200g** Bistec Ranchero",
      category: "Arriba- Spezialitäten",
      price: 13.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Costillas 500g**",
      category: "Arriba- Spezialitäten",
      price: 11.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fileto de Cerdo 200g**",
      category: "Arriba- Spezialitäten",
      price: 12.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "200g** Bistec Arriba Mexico",
      category: "Arriba- Spezialitäten",
      price: 13.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "200g** Steak nach Art des Hauses",
      category: "Arriba- Spezialitäten",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "200g** Mexico-Steak",
      category: "Arriba- Spezialitäten",
      price: 11.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Arriba Mexico-Grillteller",
      category: "Arriba- Spezialitäten",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Cerdo Almendrado",
      category: "Arriba- Spezialitäten",
      price: 11.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Puntas Res a la Mexicana",
      category: "Arriba- Spezialitäten",
      price: 12.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Filetto Mexicano",
      category: "Arriba- Spezialitäten",
      price: 16.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Tres Muchachos",
      category: "Arriba- Spezialitäten",
      price: 17.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Grillplatte für 2 Personen",
      category: "Arriba- Spezialitäten",
      price: 30.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fajitas de Pollo",
      category: "Faitajs",
      price: 12.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fajitas de Carne",
      category: "Faitajs",
      price: 13.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fajitas de Cerdo",
      category: "Faitajs",
      price: 11.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fajitas Combinadas",
      category: "Faitajs",
      price: 14.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fajitas Vegetarian",
      category: "Faitajs",
      price: 10.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fajitas Camarones",
      category: "Faitajs",
      price: 15.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chicken- Burger",
      category: "Spezial Burger (125g.)",
      price: 6.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Hamburger",
      category: "Spezial Burger (125g.)",
      price: 6.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Cheese-Burger",
      category: "Spezial Burger (125g.)",
      price: 7.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Texas Chili-Burger",
      category: "Spezial Burger (125g.)",
      price: 7.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Bacon-Burger ",
      category: "Spezial Burger (125g.)",
      price: 7.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Mexican-Burger",
      category: "Spezial Burger (125g.)",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: " Arriba Mexico-Burger",
      category: "Spezial Burger (125g.)",
      price: 9.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gigant Burger",
      category: "Gigant Burger (227g.)",
      price: 9.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gigant-Cheese-Burger",
      category: "Gigant Burger (227g.)",
      price: 11.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gigant-Mexican-Burger",
      category: "Gigant Burger (227g.)",
      price: 12.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gigant-Bacon-Burger",
      category: "Gigant Burger (227g.)",
      price: 12.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Mexicana",
      category: "Pasta",
      price: 6.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Shrimps & Veggie Pasta",
      category: "Pasta",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Beef-Carne",
      category: "Pasta",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Primavera",
      category: "Pasta",
      price: 6.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Chicken",
      category: "Pasta",
      price: 6.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta California",
      category: "Pasta",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Chorico",
      category: "Pasta",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Camerones",
      category: "Pasta",
      price: 7.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Meryanos",
      category: "Pasta",
      price: 7.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Mythra",
      category: "Pasta",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Kamalas",
      category: "Pasta",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Salas",
      category: "Pasta",
      price: 5.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Camarones Mexicana",
      category: "Pescado-Fischgerichte",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Fischpfanne",
      category: "Pescado-Fischgerichte",
      price: 13.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Salmone con Nopales",
      category: "Pescado-Fischgerichte",
      price: 13.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Salmone al Tequila",
      category: "Pescado-Fischgerichte",
      price: 13.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: " Salmone California",
      category: "Pescado-Fischgerichte",
      price: 13.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Junior Burger",
      category: "Kinder-Menü",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Crazy Chicken",
      category: "Kinder-Menü",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chicken Nuggets",
      category: "Kinder-Menü",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Pasta Chicken",
      category: "Kinder-Menü",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Mini-Hüftsteak 120g**",
      category: "Für den kleinen Hunger",
      price: 8.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lady-Filetsteak 120g**",
      category: "Für den kleinen Hunger",
      price: 12.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Espresso",
      category: "Getränke-Hot Drinks",
      price: 1.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Espresso Macchiato",
      category: "Getränke-Hot Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "doppelter Espresso",
      category: "Getränke-Hot Drinks",
      price: 3.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Café Crème",
      category: "Getränke-Hot Drinks",
      price: 2.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Milchkaffee",
      category: "Getränke-Hot Drinks",
      price: 3.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Cappuccino",
      category: "Getränke-Hot Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Amaretto Cappuccino",
      category: "Getränke-Hot Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Bailays Cappuccino",
      category: "Getränke-Hot Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Latte Macchiato",
      category: "Getränke-Hot Drinks",
      price: 3.20,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Mexican Kaffee",
      category: "Getränke-Hot Drinks",
      price: 4.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "BIO FRÜCHTE NATUR",
      category: "Getränke-Hot Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "BIO GRÜNTEE JASMIN Blatt",
      category: "Getränke-Hot Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "English Select Ceylon Orange PEKOE blatt",
      category: "Getränke-Hot Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "PFEFFERMINZBLÄTTER",
      category: "Getränke-Hot Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "KAMILLENBLÜTEN",
      category: "Getränke-Hot Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Chai Latte Classic",
      category: "Getränke-Hot Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Schoko Chai Latte",
      category: "Getränke-Hot Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Glühwein",
      category: "Getränke-Hot Drinks",
      price: 2.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Grog",
      category: "Getränke-Hot Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Barcadi & Cola",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Gin-Tonic³",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Whisky-Cola",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Wodka-Lemon",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Southern-Ginger",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Batida-Kirsch",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Cuba Libre",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Campari",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Red Bull-Wodka",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Red Bull-Prosecco",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Red Bull-Campari",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Sierra Tequila Silver Palomo",
      category: "Long Drinks",
      price: 6.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
      Product(
      name: "Henkell Trocken Piccolo(Fl. 0.2l)",
      category: "Long Drinks",
      price: 4.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
      Product(
      name: "Henkell Trocken(Fl. 0.75l)",
      category: "Long Drinks",
      price: 18.00,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Concha y Toro(CHILENISCH)-Fl. 0.75l",
      category: "Long Drinks",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
      Product(
      name: "Concha y Toro(CHILENISCH)Blance-Fl. 0.75l",
      category: "Long Drinks",
      price: 14.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "L.A. Cetto rot(MEXIKANISCH)-Fl. 0.75l",
      category: "Long Drinks",
      price: 15.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "L.A. Cetto weiß(MEXIKANISCH)-Fl. 0.75l",
      category: "Long Drinks",
      price: 15.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Concha y Toro(Offene Weine)-0.2l",
      category: "Long Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Concha y Toro(Offene Weine)-0.5l",
      category: "Long Drinks",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Concha y Toro(Sauvignon Blanc)-0.2l",
      category: "Long Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Concha y Toro(Sauvignon Blanc)-0.5l",
      category: "Long Drinks",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Concha y Toro Rosé -0.2l",
      category: "Long Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Concha y Toro Rosé-0.5l",
      category: "Long Drinks",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
     Product(
      name: "Dunviro Rioja(Spanischer Rotwein)-0.2l",
      category: "Long Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
       Product(
      name: "Dunviro Rioja(Spanischer Rotwein)-0.5l",
      category: "Long Drinks",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Dunviro Rioja(Spanischer Weißwein trocken)-0.2l",
      category: "Long Drinks",
      price: 3.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Dunviro Rioja(Spanischer Weißwein trocken)-0.5l",
      category: "Long Drinks",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lambrusco(Italienischer Perlwein,mild und süß)-0.2l",
      category: "Long Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Lambrusco(Italienischer Perlwein,mild und süß)-0.5l",
      category: "Long Drinks",
      price: 7.90,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Sangria(Weinhaltiges Getränk mit Früchten)-0.2l",
      category: "Long Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
    Product(
      name: "Weinschorle(Weinhaltiges Getränk)-0.2l",
      category: "Long Drinks",
      price: 3.50,
      isPopular: false,
      isRecommended: false,
      isRecentlyadded: false,
      isDrink: false,
      imaUrl: 'images/biryani.jpg',
    ),
  ];
}
